version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "80:5000"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:E6rnOlLX8yX434s@db/db
    depends_on:
      - db
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=E6rnOlLX8yX434s
      - POSTGRES_DB=db
    ports:
      - "5432:5432"

volumes:
  postgres_data: